//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class placedorder
    {
        public int issueid { get; set; }
        public Nullable<int> customerid { get; set; }
        public Nullable<int> brandid { get; set; }
        public Nullable<System.DateTime> orderdate { get; set; }
        public Nullable<System.DateTime> receiveddate { get; set; }
        public string comments { get; set; }
    
        public virtual lapbrand lapbrand { get; set; }
        public virtual logintable logintable { get; set; }
    }
}
